### ISSUE TITLE
License mismatch?

### ISSUE THREAD

**Issue by Hugovdberg** [mbakker7/timml#1]
Both the LICENSE file and the manual mention timml is released under the MIT license, timml/ml.py mentions being released under the GNU LPGL license [sic]. Is this a deliberate decision or a license change that hasn't been fully implemented yet?

**Comment by mbakker7** [comment]
This was indeed a license change that wasn't fully implemented. Is fixed now. Thanks. Any reason you are interested in the specific license (most people don't even look at it)?
