### ISSUE TITLE
Stop github pages deployment

### ISSUE THREAD

**Issue by dbrakenhoff** [mbakker7/timml#102]
It seems the github pages deployment is still trying to run, see [here](https://github.com/mbakker7/timml/deployments/github-pages). We should stop that somehow, probably somewhere under Settings...

**Comment by mbakker7** [comment]
I found this option for unpublishing a GitHub-pages site: https://docs.github.com/en/pages/getting-started-with-github-pages/unpublishing-a-github-pages-site
But apparently there is also such a thing as deleting a GitHub-pages site, for which they point you to this link: https://docs.github.com/en/pages/getting-started-with-github-pages/deleting-a-github-pages-site
Not sure yet which one to do, or both.

**Comment by dbrakenhoff** [comment]
Hmmm, probably start with the first option, and if an entry remains in Settings > Pages, you can try deleting it by setting the source to None.

**Comment by mbakker7** [comment]
First option didn't exist, so I followed these instructions: https://docs.github.com/en/github-ae@latest/pages/getting-started-with-github-pages/unpublishing-a-github-pages-site
Let's see whether that did the trick next time we have a release.
