### ISSUE TITLE
PolygonImhomMaq error when points are specified in clockwise direction

### ISSUE THREAD

**Issue by ghost** [mbakker7/timml#17]
When creating an inhomogeneity and the xy-coordinates are ordered in clockwise direction, an error occurs when the model is solved. When both the inhomogeneity and the model are confined a LinalgError is thrown. If the inhomogeneity is confined but the model is semi-confined, an AssertionError that hstar needs to be set is thrown. 

Providing the coordinates in clockwise direction causes the computation points on the inside and outside of the inhomogeneity to be switched, the inside point is located on the outside, and vice versa. This snippet of code reproduces the AssertionError I describe:

```{python}
xy = [(-10, -5), (-10, 5), (10, 5), (-10, -5)]
ml =  timml.ModelMaq(z=[1, 0, -1], c=[100], topboundary="semi", hstar=1.0)
inhom = timml.PolygonInhomMaq(ml, xy)
w = timml.Well(ml)
ml.solve()
```

**Comment by jentjr** [comment]
A simple fix might be to check the order in which the vertices were entered. Though that looks like what the last part of compute_z1z2 is doing. 

    def vertice_order(xy):
        """check the order of entered vertices"""
        sign = 0
        n = len(xy)
        for i in range(n):
            j = (i + 1) % n
            sign += (xy[i][0]*xy[j][1] - xy[j][0]*xy[i][1])
            
        return sign


    def compute_z1z2(xy):
    """Returns z1 and z2 of polygon, in clockwise order"""
    
    # check that vertices were entered counter-clockwise
    # if not, reverse the order
    sign = vertice_order(xy)
    if sign < 0 :
        xy[::-1]
    
    x, y = list(zip(*xy))
    if x[0] == x[-1] and y[0] == y[-1]:  # In case last point is repeated
        x = x[:-1];
        y = y[:-1]
    z1 = np.array(x) + np.array(y) * 1j
    index = list(range(1, len(z1))) + [0]
    z2 = z1[index]
    Z = 1e-6j
    z = Z * (z2[0] - z1[0]) / 2.0 + 0.5 * (z1[0] + z2[0])
    bigZ = (2.0 * z - (z1 + z2)) / (z2 - z1)
    bigZmin1 = bigZ - 1.0
    bigZplus1 = bigZ + 1.0
    angle = np.sum(np.log(bigZmin1 / bigZplus1).imag)
    if angle < np.pi:  # reverse order
        z1 = z1[::-1]
        z2 = z2[::-1]
    return z1, z2

**Comment by mbakker7** [comment]
fixed in https://github.com/mbakker7/timml/commit/809cac265d4e8b311aca5e34a2d8b0878928b4df
including example in notebook3
