### ISSUE TITLE
Add PolyAreaSink

### ISSUE THREAD

**Issue by jentjr** [mbakker7/timml#20]
Mark, I have tried to implement a PolyAreaSink class in a development branch by following Section 8.26 from Analytical Groundwater Mechanics (Strack, 2017). I've also started a [notebook](https://github.com/jentjr/timml/blob/develop/notebooks/test_polyareasink.ipynb) for some test cases. It appears to be working correctly since the far field behavior approaches that of a well with extraction rate equal to gamma*A. My knowledge of the analytical element method is very basic at the moment though, so I am unsure. Anyways, hopefully this can be a starting point to add the PolyAreaSink class.

Thanks,
Justin

**Comment by mbakker7** [comment]
Implemented polygonal areasinks in areasink branch by implementing option to specify recharge inside inhomogeneity with https://github.com/mbakker7/timml/commit/c11ba79a19cd1e3b21ca8beb1e820d88bf82f18f

**Comment by mbakker7** [comment]
merged into master
