### ISSUE TITLE
well capzone function is ignoring parameter assignments

### ISSUE THREAD

**Issue by dpphat** [mbakker7/timml#27]
It looks like line 174 of well.py should be passing variables assigned to capzone, however, it is written as follows:

        xyzt = timtracelines(self.model, xstart, ystart, zstart, -np.abs(hstepmax), \
                             vstepfrac=0.2, tmax=tmax, nstepmax=100, silent='.')

i.e., some values such as nstepmax and vstepfrac are hard-coded.

**Comment by Hugovdberg** [comment]
This will be fixed in #22, I noticed it as well

**Comment by mbakker7** [comment]
Fixed in #22, now in master. Thanks for reporting.

**Comment by dpphat** [comment]
Thanks so much!
