### ISSUE TITLE
Cleanup tests

### ISSUE THREAD

**Issue by Hugovdberg** [mbakker7/timml#30]
Is there a reason that tests/test_import.py tries to import timml and then converts all errors to an `AssertionError`? I think that it's cleaner to catch the more specific `ImportError`, or simply just do the import and let `pytest` know specifically which error occurred, if any.

https://github.com/mbakker7/timml/blob/b15fa2e56990d3e298e98dcd79c27008face6efc/tests/test_import.py#L1-L6

In my opinion it could be replaced with:

```python
def test_import():
    import timml
```

**Comment by mbakker7** [comment]
Good point. Not sure why it was this way. Changed according to your suggestion.
