### ISSUE TITLE
Remove storeinput?

### ISSUE THREAD

**Issue by Hugovdberg** [mbakker7/timml#32]
In three places a `storeinput` method is defined, that stores the input arguments and local variables from the caller in the class using the `inspect` module. As far as I can see, these values are never used anywhere, but stored in almost every `timml` object. Inspection is not very good for performance, and keeping all these unused objects around doesn't make sense to me. Is there a good reason to still keep it in the code, or should we just remove it?

**Comment by mbakker7** [comment]
storeinput is used to generate an import file after a model is built interactively or using a GUI. 
a tests needs to be written to make sure it is used consistently.

**Comment by mbakker7** [comment]
I close it now so I can change the title
