### ISSUE TITLE
inhomogeneity in Model3D

### ISSUE THREAD

**Issue by PilbaraPanther** [mbakker7/timml#46]
Does the Polygonal inhomogeneity work with Model3D type models? I can only get it to work with ModelMaq type models and can't find any reference or examples on how to set it up

thanks

**Comment by mbakker7** [comment]
Yes, it works, but I guess TimML doesn't have a helper function for that like for ModelMaq. You can look at the helper function for ModelMaq and try to write your own for Model3D. If you do so and succeed, please submit a pull request. I can try as well, but can not promise I will get to  it before the holidays.

**Comment by mbakker7** [comment]
Merged into master
