### ISSUE TITLE
IndexError: list index out of range 

### ISSUE THREAD

**Issue by brixel-1984** [mbakker7/timml#52]
Hi,
I just installed timml and tried a few notebooks but I get an IndexError  with the contour function when plotting some of the results. It seems related to the number of items in the list to create the figure legend.
Did anyone note this?
B
ps: I run timml from a conda environment with python 3.10.6 installed on debian 11

**Comment by mbakker7** [comment]
Dear Bernard,

Thanks. I have seen that error, but it skipped my mind.
It has to do with a change in matplotlib in adding a legend. So not
important, but annoying. I have to fix that. Will do soon,

Mark

**Comment by brixel-1984** [comment]
Dear Mark,
Thanks, I am looking forward to use your code!
Bernard
