### ISSUE TITLE
HeadLineSinkString cannot take multiple layers

### ISSUE THREAD

**Issue by mbakker7** [mbakker7/timml#8]
ml = ModelMaq(kaq=[1, 2], z=[20, 12, 10, 0], c=[1000])
    ls = HeadLineSinkString(ml, xy=[(0, 0), (1, 0), (2, 0), (3, 0), (4, 0)], hls = 7, layers=[0, 1],  order=2)
    ml.solve()
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-4-48a52e4ce398> in <module>()
    ----> 1 ml.solve()
    
    /Users/mark/git/timml/timml/model.py in solve(self, printmat, sendback, silent)
        146         '''Compute solution'''
        147         # Initialize elements
    --> 148         self.initialize()
        149         # Compute number of equations
        150         self.Neq = np.sum([e.Nunknowns for e in self.elementlist])
    
    /Users/mark/git/timml/timml/model.py in initialize(self)
         23         self.aq.initialize()
         24         for e in self.elementlist:
    ---> 25             e.initialize()
         26 
         27     def add_element(self, e):
    
    /Users/mark/git/timml/timml/linesink.py in initialize(self)
        505         # self.pc = np.array([ls.pc for ls in self.lslist]).flatten()
        506         if len(self.hls) == 1:
    --> 507             self.pc = self.hls * self.aq.T[self.pylayers] * np.ones(self.Nparam)
        508         elif len(self.hls) == self.Nls:  # head specified at centers
        509             self.pc = (self.hls[:, np.newaxis] * self.aq.T[self.pylayers]).flatten()
    
    ValueError: operands could not be broadcast together with shapes (2,) (24,)

**Comment by Hugovdberg** [comment]
Merged from #28:
When assigning a label to HeadLineSinkString it returns an error that the label is already used once it tries to create the second element. It should either append an index to the label, or accept a list of labels (which it doesn't, it now raises an error that list is an unhashable type, which cannot be used a key in a dictionary)

**Comment by mbakker7** [comment]
label is fixed in master. I think layers also work (for a while already), but need to check and add to notebook.

**Comment by mbakker7** [comment]
HeadLineSinkString can take a list of layers with the same length as the number of line-sinks in the string to make, for example, a slanted well. See example in Notebook 4.

**Comment by mbakker7** [comment]
HeadLineSinkString can now also take list of layers. When list is shorter than number of layers, all segments are places in all specified layers. 

https://github.com/mbakker7/timml/commit/ef1e3ed92c577b0e0e0cde31cea1c98a0c8b8f8f
