### ISSUE TITLE
Numba deprecation warning

### ISSUE THREAD

**Issue by dbrakenhoff** [mbakker7/timml#87]
Tests are throwing warnings:

`Encountered the use of a type that is scheduled for deprecation: type 'reflected list' found for argument 'labda' of function 'disbesldho'.`

We should fix that sometime soon, probably.

**Comment by mbakker7** [comment]
Just curious, what is wrong with
```
if (layer in self.layers)
```
?

**Comment by dbrakenhoff** [comment]
fixed by 9c261b716a55faca4ff0a01ce284b25a5b0c1e28
